### ISSUE TITLE
Identify the Submit button correctly

### ISSUE THREAD

**Issue by Mr-DJ** [Mr-DJ/biopass-extension#4]
The current script is not able to identify the submit button accurately returning undefined on some websites. This may be caused because of when or where the findSubmit function is invoked. Please look into this issue.

**Comment by NR-NJN** [comment]
![image](https://github.com/Mr-DJ/biopass-extension/assets/66485604/adc9e1f9-99d1-4fab-beb3-9a2226ce8e9a)


function fix
